# Generated by Django 5.2 on 2025-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='minimum_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
